### ISSUE TITLE
Module missing in 7.0.1

### ISSUE THREAD

**Issue by siegfried** [input-output-hk/cardano-graphql#768]
### Summary

After upgrade Typescript client from 7.0.0 to 7.0.1, I got this error.

```
Type error: Cannot find module '@cardano-graphql/client-ts' or its corresponding type declarations.

import type { ProtocolParams, TransactionOutput } from '@cardano-graphql/client-ts'
```

### Actual Result

Cannot import module.

### Expected Result

Should be able to import without any change since this is a patch update.

### Environment

```
{
  os: {
    arch: 'x64',
    cpus: { count: 12, model: 'Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz' },
    release: '21.6.0',
    totalMem: 68719476736,
    type: 'Darwin'
  },
  version: '6.2.0'
}
```

### Platform

- [ ] Linux (Ubuntu)
- [ ] Linux (Other)
- [ ] macOS
- [ ] Windows

### Platform version

macOS

### Runtime

- [X] Node.js
- [ ] Docker

### Runtime version

v18.9.0

**Comment by rhyslbw** [comment]
It looks like your project is not finding the whole package. Can you see it in your `node_modules`?

**Comment by siegfried** [comment]
Yes, I can see it. I also tried to remove `node_modules` and reinstall all the packages. `7.0.0` can work but `7.0.1` cannot.

**Comment by siegfried** [comment]
This issue still exists on `7.0.2`.

**Comment by siegfried** [comment]
Update: change `@cardano-graphql/client-ts` to `@cardano-graphql/client-ts/api` can work.
